### ISSUE TITLE
UX: Design Self Create Flow Customize App Functionality (e.g. logo, colors, dark/light mode?)

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-treasury-dashboard#123]
# Background
Our Treasury App currently lacks a dedicated section for admins to configure the look and feel of their application (e.g. logo, color, dark/light them, etc). This limits their flexibility to customize their application and requires custom engineering time to set up new instances.

# UX Need
We need a way for admins to customize the look and feel of their Treasury Dashboard. This includes:

- Uploading their own logo
- Choosing the colors
- Choosing the theme (dark/light)

# Acceptance Criteria 

- [x] Create mockups and user flow with the proposed UX solution 
- [x] Identify and document any potential edge cases or error handling scenarios
- [x] Present the proposed solution and gather feedback from the portal dev team
- [x] Review [development task](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/124) and confirm the requirements meet the final UX approach

**Comment by FREZZZBE** [comment]
I think settings for this is more improtat then creation flow. Because you can Add and Edit form here. On creation you can only Add

And im not even shure if we need to add this on creation flow to simplify it. What do you think? @ori-near 

Figma | [Prototype](https://www.figma.com/proto/hNg69dceqgi7yMYtovrbYc/%F0%9F%8F%A6-Multisig-Treasury-Application?page-id=&node-id=5348-18958&node-type=frame&viewport=-737%2C-631%2C0.12&t=EfWVockYzgqvaNJn-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=848%3A12117)

Here is already made React color picker i used in prototype and relly like [Link](https://www.npmjs.com/package/react-colorful)

https://github.com/user-attachments/assets/4204d59d-7735-4109-9d75-4db6f4bd65f7

**Comment by ori-near** [comment]
Hey @FREZZZBE – thank you, looks good. @Megha-Dev-19 – can you confirm this solution works or if we need to follow any of the BOS widgets here?

Also @FREZZZBE – can you please add error state (e.g. "Invalid logo. Please upload a PNG, JPG, or SVG file for your logo that is exactly 256x256 px") if user uploads unsupported format or image not in the right requirements?

**Comment by FREZZZBE** [comment]
[Figma](https://www.figma.com/design/hNg69dceqgi7yMYtovrbYc/%F0%9F%8F%A6-Multisig-Treasury-Application?node-id=5348-18958&node-type=frame&t=8tY19iWnDUFN8hVh-11) Here is error example

![Image](https://github.com/user-attachments/assets/d4600010-0c44-4c9f-990c-ddf3e49d4bdb)
